### ISSUE TITLE
[docker] run containers as a non-root user

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#109]
It's not the best idea to run docker containers as root in production: https://americanexpress.io/do-not-run-dockerized-applications-as-root/

We should create user `openwisp` and run the containers as `openwisp` user with access to only the content it needs.

**Comment by nepython** [comment]
@atb00ker, I would like to take up this issue though I don't have prior experience working on docker. (Time to try out few new things:smiley:) So please correct me when I would go wrong.
