### ISSUE TITLE
quick deployment does not work - no images found

### ISSUE THREAD

**Issue by stefangweichinger** [openwisp/docker-openwisp#134]
Tried to edit `.env` and run `make start`, this gives me:

```
$  make start
Downloading OpenWISP images...
Error response from daemon: No such image: registry.gitlab.com/openwisp/docker-openwisp/openwisp-base:latest
Error response from daemon: No such image: registry.gitlab.com/openwisp/docker-openwisp/openwisp-nfs:latest
Error response from daemon: No such image: registry.gitlab.com/openwisp/docker-openwisp/openwisp-controller:latest
[..]
```

How to fix that, pls?

**Comment by atb00ker** [comment]
Hi @stefangweichinger 

Sorry about that, it was a problem from our end, we are in the process of moving our docker registry, I've uploaded some temporary for you for now, please try again.

**Comment by atb00ker** [comment]
(Feel free to open if you get stuck with something else)

**Comment by stefangweichinger** [comment]
Thanks @atb00ker , download OK now. I try to proceed now ...

**Comment by stefangweichinger** [comment]
So far no success. Either with your `.env` or a version with edited variables: I don't get a WebGUI displayed.
I assume I wouldn't need Radius and "topology" for a small test installation?

I am just in the process to test drive OpenWISP for a customer and would like to get some impression and overview.

I pulled the images: ok ... then I had to adjust the network not to overlap, and the exported ports to 50080/50443.
Now the stack starts, but no success:

```
nginx_1       | 2020/10/15 15:16:02 [error] 42#42: *26 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.28.0.1, server: , request: "GET / HTTP/1.1", host: "0.0.0.0:50080"
nginx_1       | [0521e4a87f9e] - - [15/Oct/2020:15:16:02 +0530] "GET / HTTP/1.1" status: 404 555 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" http_x_forwarded_for: - - remote_addr: 172.28.0.1 - realip_remote_addr: 172.28.0.1 - real_ip: 172.28.0.1
nginx_1       | 2020/10/15 15:16:02 [error] 42#42: *26 open() "/etc/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.28.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "0.0.0.0:50080", referrer: "http://0.0.0.0:50080/"
nginx_1       | [0521e4a87f9e] - - [15/Oct/2020:15:16:02 +0530] "GET /favicon.ico HTTP/1.1" status: 404 555 "http://0.0.0.0:50080/" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" http_x_forwarded_for: - - remote_addr: 172.28.0.1 - realip_remote_addr: 172.28.0.1 - real_ip: 172.28.0.1
nginx_1       | 2020/10/15 15:16:58 [error] 42#42: *26 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.28.0.1, server: , request: "GET / HTTP/1.1", host: "0.0.0.0:50080"
```

Do you hardcode the nginx-ports somewhere, maybe?

**Comment by atb00ker** [comment]
Can you try `make clean`, then `make start`, if it persists, can you please let me know what all things you have changed, based on that, I will investigate.

**Comment by atb00ker** [comment]
P.S:
I just changed the following lines in `docker-compose`:

    ports:
      - "80:80"
      - "443:443"

to

    ports:
      - "50080:80"
      - "50443:443"

**Comment by stefangweichinger** [comment]
> Can you try `make clean`, then `make start`, if it persists, can you please let me know what all things you have changed, based on that, I will investigate.

Will do tomorrow, thanks so far. I will simply use your `.env` and show/post logs.

**Comment by stefangweichinger** [comment]
I only edited the ports as you did and the network:

```
networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24
```

Then I start the stack, wait a bit and try to open `http://0.0.0.0:50080`, nginx logs:




```
HTTP/1.1" status: 200 32 "-" "Wget" http_x_forwarded_for: - - remote_addr: 172.18.1.6 - realip_remote_addr: 172.18.1.6 - real_ip: 172.18.1.6
nginx_1       | 2020/10/15 22:36:52 [error] 42#42: *55 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.18.1.1, server: , request: "GET / HTTP/1.1", host: "0.0.0.0:50080"
```

**Comment by atb00ker** [comment]
Completely forgot about replying to you, `http://0.0.0.0:50080` has nothing.
You must have set a dashboard URL `dashboard.openwisp.org` by default. Hence your site is at ``http://dashboard.openwisp.org:50080``

**Comment by stefangweichinger** [comment]
Oh, yes, correct. Now I get the login ;-)  thanks so far
