### ISSUE TITLE
[module] Add firmware-upgrader module

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#138]
https://github.com/openwisp/openwisp-firmware-upgrader

**Comment by b-thebest** [comment]
Could you please elaborate more about issue and what needs to be done in detail.

**Comment by atb00ker** [comment]
Hi, I want to add the firmware module in docker-openwisp: https://github.com/openwisp/openwisp-firmware-upgrader
That would mean,
- create a fireware-upgrader docker image (example: image for controller: https://github.com/openwisp/docker-openwisp/tree/master/build/openwisp_controller)
- add the image to docker-compose (example: https://github.com/openwisp/docker-openwisp/blob/master/docker-compose.yml#L21-L33)
- Ensure that when firmware upgrader works with `make develop` and `make start` command.
- Write automated tests.
- Add information about the new module in documentation

Note:
- You need to understand what the firmware-upgrader module does to test it properly, so please invest some time on that.
- Ensure that the firmware upgrader can be turned off. (i.e it's an optional module -- we can worry about this point when some basics are done, I'd help you ensure this! :smile: )
