### ISSUE TITLE
[ux] Ensure changing default org does not fail restarting

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#145]
If the default org in the database is changed, it shouldn't fail images from starting again because VPN cannot find the organization with the `default` name, we should ignore this error! :smile:

**Comment by Sparkxxx** [comment]
As you know I'm just starting with OpenWisp so I don't know the internals but what is the porpouse of having a way to change the default org in the interface if it does not update all the rest of the services?

**Comment by atb00ker** [comment]
@Sparkxxx It updates inside the application, the .env is just a config file used to start the docker containers, it's not linked in anyway to the configurations inside the application! :smile:

**Comment by Sparkxxx** [comment]
Than maybe a note/modal/something when changing the value in the application to notify/remember me to change x/y/z .env values asap before restarting the docker-compose would be the way to go?

**Comment by atb00ker** [comment]
Should be fixed in the next release (0.5.0) :smile:
