### ISSUE TITLE
Error response from daemon: No such image: registry.gitlab.com (Docker Images failed to download)

### ISSUE THREAD

**Issue by tnaveenchand** [openwisp/docker-openwisp#148]
Hi,

I'm facing issue while installing Open-wisp via Docker (auto install.sh script).

Also i have checked few forums which you mentioned that this issue has been resolved but ,I'm still facing issue on Debian 10,

Below are few logs for your reference any support on this is much appreciated.

alexius@alex:~/Videos/docker-openwisp$ sudo ./auto-install.sh

Welcome to OpenWISP auto-installation script.
Please ensure following requirements:
- Fresh instance
- 2GB RAM (Min)
- Debian 10 / Ubuntu 18.04
- Root privileges

Checking your system capabilities...                                   done
Setting up dependencies...                                             done
Setting up docker...                                                   done
Setting up docker-compose...                                           done
Downloading docker-openwisp...                                         done

OpenWISP Configuration:
OpenWISP Version (leave blank for latest):
Do you have .env file? Enter filepath (leave blank for ad-hoc configuration):
(1/7) Enter dashboard domain: alex.play
(2/7) Enter controller domain (blank for controller.play):
(3/7) Enter radius domain (blank for radius.play, N to disable module):
(4/7) Enter topology domain (blank for topology.play, N to disable module):
(5/7) Enter OpenVPN domain (blank for vpn.play, N to disable module):
(6/7) Site manager email: admin@alex.play
(7/7) Enter letsencrypt email (leave blank for self-signed certificate):

Configuring docker-openwisp...                                         done
Starting images docker-openwisp (this will take a while)...            error
Starting openwisp failed.
Check logs at /opt/openwisp/autoinstall.log
alexius@alex:~/Videos/docker-openwisp$ cat /opt/openwisp/autoinstall.log

Checking your system capabilities...

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://security.debian.org/debian-security buster/updates InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Reading package lists...
Building dependency tree...
Reading state information...
All packages are up to date.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

lsb-release is already the newest version (10.2019051400).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Setting up dependencies...

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
gcc is already the newest version (4:8.3.0-1).
git is already the newest version (1:2.20.1-2+deb10u3).
libffi-dev is already the newest version (3.2.1-9).
make is already the newest version (4.2.1-1.2).
python3-pip is already the newest version (18.1-5).
python3 is already the newest version (3.7.3-1).
python3-dev is already the newest version (3.7.3-1).
libssl-dev is already the newest version (1.1.1d-0+deb10u5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Setting up docker...
Setting up docker-compose...
Requirement already satisfied: docker-compose in /usr/lib/python3/dist-packages (1.21.0)
Downloading docker-openwisp...
Cloning into '/opt/openwisp/docker-openwisp'...
Configuring docker-openwisp...
Starting images docker-openwisp (this will take a while)...
make: Entering directory '/opt/openwisp/docker-openwisp'
Downloading OpenWISP images...
Error response from daemon: No such image: registry.gitlab.com/openwisp/docker-openwisp/openwisp-base:latest
Error response from daemon: No such image: registry.gitlab.com/openwisp/docker-openwisp/openwisp-nfs:latest
Error response from daemon: No such image: registry.gitlab.com/openwisp/docker-openwisp/openwisp-controller:latest
Error response from daemon: No such image: registry.gitlab.com/openwisp/docker-openwisp/openwisp-dashboard:latest
Error response from daemon: No such image: registry.gitlab.com/openwisp/docker-openwisp/openwisp-freeradius:latest
Error response from daemon: No such image: registry.gitlab.com/openwisp/docker-openwisp/openwisp-nginx:latest
Error response from daemon: No such image: registry.gitlab.com/openwisp/docker-openwisp/openwisp-openvpn:latest
Error response from daemon: No such image: registry.gitlab.com/openwisp/docker-openwisp/openwisp-postfix:latest
Error response from daemon: No such image: registry.gitlab.com/openwisp/docker-openwisp/openwisp-radius:latest
Error response from daemon: No such image: registry.gitlab.com/openwisp/docker-openwisp/openwisp-topology:latest
Error response from daemon: No such image: registry.gitlab.com/openwisp/docker-openwisp/openwisp-websocket:latest
make: *** [Makefile:14: pull] Error 1
make: Leaving directory '/opt/openwisp/docker-openwisp'

**Comment by atb00ker** [comment]
Hmm, I see images at https://gitlab.com/openwisp/docker-openwisp/container_registry
and I am able to pull on my end.

Can you try ensure your docker setup is correct and you are able to pull other images?
What does manually typing `docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-dashboard` do?

**Comment by tnaveenchand** [comment]
Docker is working fine and i could pull the other images:

alexius@alex:~/Videos/docker-openwisp$ sudo docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-dashboard
Using default tag: latest
latest: Pulling from openwisp/docker-openwisp/openwisp-dashboard
45b42c59be33: Already exists
f875e16ab19c: Already exists
6997dda769d8: Already exists
564b60cf6c28: Already exists
e55c09d2e3e0: Already exists
2cbf5f069098: Pull complete
d7f32e138c05: Pull complete
1fa385350bd7: Pull complete
15c896bd50c8: Pull complete
40e3e8918074: Pull complete
74467c7d3f36: Pull complete
c69b7a860d0c: Pull complete
4d9b76ecb3e4: Pull complete
Digest: sha256:2381e8e3549b42ab91173b0354bbdae30deae1cd32b1cffdf246f19e09aeacd1
Status: Downloaded newer image for registry.gitlab.com/openwisp/docker-openwisp/openwisp-dashboard:latest


Is there anyway  can you make it work automatic script auto-install.sh

**Comment by atb00ker** [comment]
Man, I am clueless why that might be happening, 
To lift your blocker, probably, you could download the images before running the script, just do:

```
docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-nfs:latest
docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-controller:latest
docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-dashboard:latest
docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-freeradius:latest
docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-nginx:latest
docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-openvpn:latest
docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-postfix:latest
docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-radius:latest
docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-topology:latest
docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-websocket:latest
```

**Comment by tnaveenchand** [comment]
Thanks Ajay for your kind support,

I did pulled the content & it seems to work now 

alexius@alex:~/Videos/docker-openwisp$ sudo docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-nfs:latest
latest: Pulling from openwisp/docker-openwisp/openwisp-nfs
4c0d98bf9879: Pull complete
6273cc0ea498: Pull complete
cf9befee675b: Pull complete
Digest: sha256:6803552b6a7388199a6b17ca047e0eab03f4a66989f5280cfcdb211c57cc3326
Status: Downloaded newer image for registry.gitlab.com/openwisp/docker-openwisp/openwisp-nfs:latest
alexius@alex:~/Videos/docker-openwisp$ sudo docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-controller:latest
latest: Pulling from openwisp/docker-openwisp/openwisp-controller
45b42c59be33: Already exists
f875e16ab19c: Already exists
6997dda769d8: Already exists
564b60cf6c28: Already exists
e55c09d2e3e0: Already exists
2cbf5f069098: Already exists
d7f32e138c05: Already exists
1fa385350bd7: Already exists
b2b4774bb487: Pull complete
Digest: sha256:c70beddc228a4a04ba4241e3e3d5ce423fb9e37fcde0b8b2e9d023947f7705f8
Status: Downloaded newer image for registry.gitlab.com/openwisp/docker-openwisp/openwisp-controller:latest
alexius@alex:~/Videos/docker-openwisp$ sudo docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-dashboard:latest
latest: Pulling from openwisp/docker-openwisp/openwisp-dashboard
Digest: sha256:2381e8e3549b42ab91173b0354bbdae30deae1cd32b1cffdf246f19e09aeacd1
Status: Image is up to date for registry.gitlab.com/openwisp/docker-openwisp/openwisp-dashboard:latest
alexius@alex:~/Videos/docker-openwisp$ sudo docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-freeradius:latest
latest: Pulling from openwisp/docker-openwisp/openwisp-freeradius
89d9c30c1d48: Already exists
65fd396cd71b: Already exists
4625b37796a3: Already exists
63900e7ed6f0: Already exists
06aac6771181: Pull complete
6bf7aeab2346: Pull complete
581ca760feb4: Pull complete
Digest: sha256:12db4644cf175d4c3220ef4bc746869b0dd65eb27ee8a2b65fe96dc3c1fd8812
Status: Downloaded newer image for registry.gitlab.com/openwisp/docker-openwisp/openwisp-freeradius:latest
alexius@alex:~/Videos/docker-openwisp$ sudo docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-nginx:latest
latest: Pulling from openwisp/docker-openwisp/openwisp-nginx
801bfaa63ef2: Pull complete
b1242e25d284: Pull complete
7453d3e6b909: Pull complete
07ce7418c4f8: Pull complete
e295e0624aa3: Pull complete
2af1110a0a68: Pull complete
c5a2f44113a0: Pull complete
Digest: sha256:166e03df4a3e6f45e5fb7dea2b094acc1b8119b0f0e9b9acb82fcc60a928f969
Status: Downloaded newer image for registry.gitlab.com/openwisp/docker-openwisp/openwisp-nginx:latest
alexius@alex:~/Videos/docker-openwisp$ sudo docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-openvpn:latest
latest: Pulling from openwisp/docker-openwisp/openwisp-openvpn
188c0c94c7c5: Already exists
e470f824352c: Already exists
d6ed0c7c142e: Already exists
74586f3c5cd4: Already exists
cb26244a2b2a: Already exists
b5a6c14c9440: Pull complete
a7536242b5e2: Pull complete
Digest: sha256:6d5fa3c735714d71f053a7520307076cbe64a6e98a03d05ee3f9209e410ee1ec
Status: Downloaded newer image for registry.gitlab.com/openwisp/docker-openwisp/openwisp-openvpn:latest
alexius@alex:~/Videos/docker-openwisp$ sudo docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-postfix:latest
latest: Pulling from openwisp/docker-openwisp/openwisp-postfix
801bfaa63ef2: Already exists
89dce780fccd: Pull complete
07a26aa2abbd: Pull complete
2a9c79b641f9: Pull complete
2a780d5b185b: Pull complete
Digest: sha256:fb993338fd0fca622eaf220b4940668d025a4ff35eee5c70ae6629f2db6a39ac
Status: Downloaded newer image for registry.gitlab.com/openwisp/docker-openwisp/openwisp-postfix:latest
alexius@alex:~/Videos/docker-openwisp$ sudo docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-radius:latest
latest: Pulling from openwisp/docker-openwisp/openwisp-radius
45b42c59be33: Already exists
f875e16ab19c: Already exists
6997dda769d8: Already exists
564b60cf6c28: Already exists
e55c09d2e3e0: Already exists
2cbf5f069098: Already exists
d7f32e138c05: Already exists
1fa385350bd7: Already exists
76534669218d: Pull complete
Digest: sha256:58eff1a91d99d6538df5e4b63ba0ac69c1c7758c3c557652fd70f18f78c5ff8b
Status: Downloaded newer image for registry.gitlab.com/openwisp/docker-openwisp/openwisp-radius:latest
alexius@alex:~/Videos/docker-openwisp$ sudo docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-topology:latest
latest: Pulling from openwisp/docker-openwisp/openwisp-topology
45b42c59be33: Already exists
f875e16ab19c: Already exists
6997dda769d8: Already exists
564b60cf6c28: Already exists
e55c09d2e3e0: Already exists
2cbf5f069098: Already exists
d7f32e138c05: Already exists
1fa385350bd7: Already exists
70ec373450d0: Pull complete
Digest: sha256:8a39806d70f888e7f2659d044966ee23a88cb76b8e430b80275af31a2a478554
Status: Downloaded newer image for registry.gitlab.com/openwisp/docker-openwisp/openwisp-topology:latest
alexius@alex:~/Videos/docker-openwisp$ sudo docker pull registry.gitlab.com/openwisp/docker-openwisp/openwisp-websocket:latest
latest: Pulling from openwisp/docker-openwisp/openwisp-websocket
45b42c59be33: Already exists
f875e16ab19c: Already exists
6997dda769d8: Already exists
564b60cf6c28: Already exists
e55c09d2e3e0: Already exists
2cbf5f069098: Already exists
d7f32e138c05: Already exists
1fa385350bd7: Already exists
a5d7225c81b0: Pull complete
0bb1a143e6a9: Pull complete
Digest: sha256:9b0cf49a32f980ff67e4e7417139ba9a77911bba3edd0861ac25758301f8ced2
Status: Downloaded newer image for registry.gitlab.com/openwisp/docker-openwisp/openwisp-websocket:latest
alexius@alex:~/Videos/docker-openwisp$ sudo vim auto-install.sh
alexius@alex:~/Videos/docker-openwisp$ sudo ./auto-install.sh

Welcome to OpenWISP auto-installation script.
Please ensure following requirements:
- Fresh instance
- 2GB RAM (Min)
- Debian 10 / Ubuntu 18.04
- Root privileges

Checking your system capabilities...                                   done
Setting up dependencies...                                             done
Setting up docker...                                                   done
Setting up docker-compose...                                           done
Downloading docker-openwisp...                                         done

OpenWISP Configuration:
OpenWISP Version (leave blank for latest):
Do you have .env file? Enter filepath (leave blank for ad-hoc configuration):
(1/7) Enter dashboard domain: alex.play
(2/7) Enter controller domain (blank for controller.play):
(3/7) Enter radius domain (blank for radius.play, N to disable module):
(4/7) Enter topology domain (blank for topology.play, N to disable module):
(5/7) Enter OpenVPN domain (blank for vpn.play, N to disable module):
(6/7) Site manager email: admin@alex.play
(7/7) Enter letsencrypt email (leave blank for self-signed certificate):

Configuring docker-openwisp...                                         done
Starting images docker-openwisp (this will take a while)...            done

Your setup is ready, your dashboard should be available on https://alex.play in 2 minutes.
You can login on the dashboard with
    username: admin
    password: admin
Please remember to change these credentials.
Random database user and password generate by the script:
   username: OCK[D3[I/%3S54R%ZmVZ9Gf6Xmc7LnB2BXZXF3UAn#H_4GtoA7
   password: rhY_9%SUK]F[+COcGI_7l63y9r6=&j[%[1**b24%S*Sil[mTnD
Please note them, might be helpful for accessing postgresql data in future.

**Comment by atb00ker** [comment]
Great, I'll try to look into why the script is not able to pull the images.

I think in your excitement, you shared your db username and password with us:

```
username: OCK[D3[I/%3S54R%ZmVZ9Gf6Xmc7LnB2BXZXF3UAn#H_4GtoA7
password: rhY_9%SUK]F[+COcGI_7l63y9r6=&j[%[1**b24%S*Sil[mTnD
```

**Comment by tnaveenchand** [comment]
Thats okay..never mind about..anyhow im gonna flash it with new settings ..

Facing issue with nginx 502 ,will check on it now and you can close this issue.

**Comment by atb00ker** [comment]
It takes about 5 minutes for openwisp to setup and start, then you wouldn't see 502.
If you have questions, feel free to ask in the mailing list: https://groups.google.com/g/openwisp

**Comment by atb00ker** [comment]
Hi, found a slight error in script, if you were putting `N` for VPN domain, it was giving 502 because of an error, fixed the script.
Just informing, because I remembered you were seeing 502! :smile:
