### ISSUE TITLE
[swagger] Show API docs

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#151]
We want to [show swagger API where exists](https://github.com/openwisp/openwisp-utils#openwisp_api_docs), for the same:
1. we need to add API in `urls.py` in the following containers: 
- openwisp-controller
- openwisp-firmware
- openwisp-radius
- openwisp-topology
- openwisp-users

2. Ensure that the API is only accessible to authenticated staff users.

**Comment by RahulPalve** [comment]
hey, @atb00ker  can you explain this in more details, what i understood is to add 
`urlpatterns += [
    url(r'^api/v1/', include('openwisp_utils.api.urls')),
]` which is url for swagger documentation to `docker-openwisp/build/openwisp-controller` and others.

**Comment by atb00ker** [comment]
Yes, you have understood it correctly, except can we use `path` instead of `url` like other urls in `urls.py` files in this project! :smile:

I would recommend recommend you to first setup and visit the openwisp-utils swagger docs page to visualize what is required here.
Then, make the changes to add the docs urls here and build the images to verify if it works as expected! :smile:
