### ISSUE TITLE
[bug] flat_json_widget missing in images

### ISSUE THREAD

**Issue by tobru** [openwisp/docker-openwisp#153]
Starting up the dashboard docker image leads into: `ModuleNotFoundError: No module named 'flat_json_widget'`. It seems that this module is missing in the base image.

**Comment by atb00ker** [comment]
Could it be that you had some old base image trying to run on new dashboard image?
Does your instance have any data?
If not, can you try to do `make clean` & `make start` again?
If it does, can you please make a backup of postgresql data and do the same?

**Comment by tobru** [comment]
Yeah right, something seem to have gone wrong at my first try. Now it starts properly. Thanks for your hints.
