### ISSUE TITLE
[bug] view topology graph broken

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#156]
Because of new authentication requirements since openwisp/openwisp-network-topology@d806fd8, 
topology graph is not working.

Currently, `OPENWISP_NETWORK_TOPOLOGY_API_AUTH_REQUIRED` has been turned off to make it work, but additional security is always better and we should create a way to allow enabling authentication.

**Comment by nemesifier** [comment]
Should be fixed on latest master, please reopen if that's not the case.
