### ISSUE TITLE
In auto-install.sh API_DOMAIN value not taking user input 

### ISSUE THREAD

**Issue by Bubby-57** [openwisp/docker-openwisp#165]
In  below else part $api should be replaced with $API_DOMAIN.

if [[ ! -f "$env_path" ]]; then
        # Dashboard Domain
        set_env "DASHBOARD_DOMAIN" "$dashboard_domain";
        # API Domain
        if [[ -z "$API_DOMAIN" ]]; then
            set_env "API_DOMAIN" "api.${domain}";
        else
            set_env "API_DOMAIN" "$api";
        fi

**Comment by atb00ker** [comment]
Thanks for reporting this! 😄

**Comment by nemesisdesign** [comment]
@atb00ker was it correct to close this?
