### ISSUE TITLE
[change] Rework celery queues to avoid slowing down tasks 

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#166]
Bug in docker-openwisp similar to https://github.com/openwisp/ansible-openwisp2/issues/273

**Comment by atb00ker** [comment]
Will do soon with https://github.com/openwisp/docker-openwisp/issues/112

**Comment by nemesisdesign** [comment]
With this we will be reorganizing the celery queues to be suited for production usage, the system needs to have several workers available which will process different queues with different priority: background tasks, monitoring checks, other generic network operations like SSH pushes or firmware upgrades.

Right now only one queue is available in docker-openwisp, but this does not work in a real production environment which has a lot of monitoring checks and time series writing operations which tend to fill the queue quickly and can cause delays to all the other background tasks which in some cases, if the delayed background tasks are critical tasks, can degrade the usability and effectiveness of the system.
