### ISSUE TITLE
[autoinstall] Add execute permission to script

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#167]
Please add +x` permission on `auto-install.sh` so that one can execute it when they pull from git.

**Comment by queenish001** [comment]
Heya @atb00ker I'm seeing this in my terminal 
![image](https://user-images.githubusercontent.com/77614377/139506654-517302eb-4b2e-4775-a1c1-cf8d8d2bc59a.png)

Is this issue already resolved?

**Comment by atb00ker** [comment]
Hi @queenish001 ,

A user just reported they want this, so I opened the issue without checking...
I'll need to check, please feel free to leave this issue for now.
