### ISSUE TITLE
[change] Add geocoding check in deployment script

### ISSUE THREAD

**Issue by devkapilbansal** [openwisp/docker-openwisp#169]
Geocoding tests are converted in deployment checks via [this PR](https://github.com/openwisp/django-loci/pull/97)

We should add this checks to ensure geocoding works as expected

Similar to https://github.com/openwisp/ansible-openwisp2/issues/310

**Comment by yashikajotwani12** [comment]
I would like to work on this.

**Comment by atb00ker** [comment]
Hey @yashikajotwani12 ,

Feel free to pick it, no assignment or permission required! :smile:

**Comment by Aryamanz29** [comment]
Hey @yashikajotwani12 are you working on this?

**Comment by yashikajotwani12** [comment]
> Hey @yashikajotwani12 are you working on this?

No, You can take this issue. 👍🏻
