### ISSUE TITLE
[feature] Implement static minification and cache invalidation

### ISSUE THREAD

**Issue by pandafy** [openwisp/docker-openwisp#187]
Similar to what has been done in https://github.com/openwisp/ansible-openwisp2/issues/216. 

But here, we want to use the storage class that have been moved to openwisp-utils in https://github.com/openwisp/openwisp-utils/pull/284

```python
STATICFILES_STORAGE = 'openwisp_utils.storage.CompressStaticFilesStorage'
```

**Comment by Aryamanz29** [comment]
I would like to work on this

**Comment by atb00ker** [comment]
In general, you don't need to wait for any permission or assignment, if you want to work on some issue, just start with it! 😄
