### ISSUE TITLE
[bug] incorrect "last_ip" in of device

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#2]
`last_ip` field of the `Device` model should point to the IP of the AP.

**Comment by atb00ker** [comment]
`update_last_ip` Function in https://github.com/openwisp/django-netjsonconfig/blob/master/django_netjsonconfig/utils.py

```
def update_last_ip(device, request):
    ip = request.META.get('REMOTE_ADDR')
```
This can be mordified to:

```
ip = request.META.get('HTTP_X_FORWARDED_FOR')
If not ip:
      ip = request.META.get('REMOTE_ADDR')
```
`HTTP_X_FORWARDED_FOR` may be a list in which case ip[0] is client id!

**Comment by nemesisdesign** [comment]
this is usually handled at webserver level, it's nginx which should set the remote ip before forwarding the request to uwsgi.

Looking at the code, I currently see:

```
    location @uwsgi {
        include uwsgi_params;
        uwsgi_pass ${APP_SERVICE}:${APP_PORT};
        uwsgi_param HTTP_X_FORWARDED_PROTO https;
    }
```

I think it should be:

```
    location @uwsgi {
        uwsgi_pass ${APP_SERVICE}:${APP_PORT};
        include uwsgi_params;
        uwsgi_param HTTP_X_FORWARDED_PROTO https;
    }
```

That is, the inclusion should happen after `uwsgi_pass` is declared, at least this is what the uwsgi documentation shows: https://uwsgi-docs.readthedocs.io/en/latest/Nginx.html.

If that wasn't the case, we would have the same problem in ansible-openwisp2, but we do not have this problem there: https://github.com/openwisp/ansible-openwisp2/blob/master/templates/nginx.j2#L38-L42.

**Comment by atb00ker** [comment]
@nemesisdesign 
I tried putting `uswgi_pass` at top like done in ansible-openwisp2, I see the same error unfortunately.

I also tried `uwsgi_param REMOTE_ADDR $http_x_forwarded_for;` and it works for the kubernetes cluster but breaks where a reverse proxy is not used (like the normal docker-compose system).

**Comment by nemesisdesign** [comment]
the second line you wrote sounds good to me, we could modify the code of openwisp if needed but i want to make sure it's really necessary before proceeding to do so, in production we should definitely use a solution like kubernetes.

**Comment by atb00ker** [comment]
One alternative option:
 we can  put `uwsgi_param REMOTE_ADDR ${REMOTE_ADDR_SOURCE};` in nginx file, where `REMOTE_ADDR_SOURCE` can be `$realip_remote_addr`, `$remote_addr` or `$http_x_forwarded_for` depending on your usecase.
The only downside of this option would be user needs to choose which option is right for them, making the usage tad bit harder for new comers! :smile:

**Comment by 2stacks** [comment]
I like having it configurable.  It would just need to be documented and the default would probably need to be whatever is most common for deploying in development (i.e. Docker Compose).  If a user is deploying to production in Kubernetes I suspect/hope they will have read the docs :smile:
