### ISSUE TITLE
docker-nginx failing 

### ISSUE THREAD

**Issue by woudanator** [openwisp/docker-openwisp#206]
Hi hope you can help with current setup I used .env to disable the radius in setup but nginx container keeps failing as its looking for domain radius.example.com and cant resolve it 

Is there a work around around this  or am I missing something in my setup file 

I see it has also been removed from the add-hoc mode where there used to be a option to disable this assistance would be much appreciated 

I use the setup.sh feature to install on a clean ubuntu 20.04 lts server

**Comment by nemesisdesign** [comment]
@woudanator you could try the latest master in which the dedicated container for openwisp-radius has been removed.

**Comment by woudanator** [comment]
thanks @nemesisdesign  giving that a swing now

**Comment by woudanator** [comment]
So i cloned the branch and tried using the auto-install.sh and get the same error on my nginx container 

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: radius.example.com
   Type:   dns
   Detail: DNS problem: NXDOMAIN looking up A for radius.example.com -
   check that a DNS record exists for this domain; DNS problem:
   NXDOMAIN looking up AAAA for radius.example.com - check that a DNS
   record exists for this domain

**Comment by woudanator** [comment]
Mmm so i did that still get same result i am going to reinstall the OS so i have a clean box and try again

**Comment by atb00ker** [comment]
Are you using your domain or are you literally using `radius.example.com`?

**Comment by atb00ker** [comment]
Also, please do:
```
sudo bash auto-install.sh --upgrade 
```

and when it asks for the version, enter `edge` instead of latest! 😄

**Comment by woudanator** [comment]
@atb00ker  you are a legened we are up and running
