### ISSUE TITLE
[change] Allow setting freeradius conf freely

### ISSUE THREAD

**Issue by nemesifier** [openwisp/docker-openwisp#210]
The conf of freeradius is very complex and everyone will need a different one, we need to be able to supply a totally different config, maybe via volumes?

**Comment by Bixilon** [comment]
What is the difference from not using openwisp in that case? Or other question: Why use openwisp, if you disable everything from it?

I use WPA2 Enterprise with active directory, not even bothered fiddeling it in in openwisp.

**Comment by nemesifier** [comment]
Should be fixed on latest master, please reopen if that's not the case.
