### ISSUE TITLE
Installation on ARM/v8 achitecture fails

### ISSUE THREAD

**Issue by nikolya-prodigy** [openwisp/docker-openwisp#218]
**Logs:**

Downloading OpenWISP images...
Starting Services...
/usr/local/lib/python3.9/dist-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
11-alpine: Pulling from mdillon/postgis
Digest: sha256:c9eca7d32159529fd191239d74f2d11cb5dac1342eab426b79493bf47f933c9b
Status: Downloaded newer image for mdillon/postgis:11-alpine
1.8-alpine: Pulling from library/influxdb
no matching manifest for linux/arm64/v8 in the manifest list entries
make: *** [Makefile:79: start] Error 1
make: Leaving directory '/opt/openwisp/docker-openwisp'

**Comment by atb00ker** [comment]
Seems like you are on an unsupported architecture: `linux/arm64/v8`, sorry but only x86 is supported right now and making sure everything works on arm is going to take some time! 😄

**Comment by boschb** [comment]
+1 for arm support.  I'm running a few OpenWrt servers, some are hardware routers, some are raspberry pi's, and all are arm... Just noticing this actually.  Anyways Docker is a drop in for OpenWrt applications, and then the next awesome move would be to manage the fleet on top of it.

I'm using a few of these:
https://firmware-selector.openwrt.org/?version=22.03.4&target=bcm27xx%2Fbcm2711&id=rpi-4

here's the architecture:
root@OpenWrt:~# uname -a
Linux OpenWrt 5.10.176 #0 SMP Sun Apr 9 12:27:46 2023 aarch64 GNU/Linux

my understanding is arm64 and aarch64 should be the ~same?  Any pointers on where to start?  Maybe I'll try and make a pull request.  This would be super useful for me.

**Comment by atb00ker** [comment]
Hi @boschb ,

>  Any pointers on where to start? 

I never got around to developing for this, but I did some PoCs.
I think adding support for arm architecture would take a bit of effort but it's possible.

The place where you'll start is:

1. Understand the directory structure of this repo
2. In the [images/](https://github.com/openwisp/docker-openwisp/tree/master/images), start changing the base images from amd64 versions to arm64 versions. (if you are on an amd64 machine, you'll need to install a bunch of things to build for another architecture, but it's easy)
3. When you've made the changes, try to start build from the make file, I am sure there will be errors because the name of the libraries/dependencies can be different.
4. I do not think many changes would be required for configuration, but if you run into a problem, try posting here: https://app.gitter.im/#/room/#openwisp_dockerize-openwisp:gitter.im for help; someone might be able to help! :smile:

**Comment by boschb** [comment]
So I got pretty far actually.  I tried doing this all on the aarch64/arm64 device itself (rasp pi4) running OpenWrt.  Honestly didn't expect it to go as far as it did. 

It got stuck on Step 38/38 apk stuff:
1.) apk packager was missing (added it)

2.) Running as non-root, fails to connect to the apk database
```
git@OpenWrt:~/docker-openwisp$  apk add --no-cache             tzdata~=2022a-r0             postgresql-client~=12.10-r0             supervisor~=4.2.0-r0
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
```

3.) Running 'make' as root fails to find some packages.
```
root@OpenWrt:/srv/git/docker-openwisp#  apk add --no-cache             tzdata~=2022a-r0             postgresql-client~=12.10-r0             supervisor~=4.2.0-r0
ERROR: unable to select packages:
  postgresql-client (no such package):
    required by: world[postgresql-client~12.10-r0]
  supervisor (no such package):
    required by: world[supervisor~4.2.0-r0]
  tzdata (no such package):
    required by: world[tzdata~2022a-r0]
```

I haven't checked if they actually don't exist for arm or not yet, but thought I thought I'd check in with progress report thus far.  Seems very close to me, but this is my first go of this build.

**Comment by atb00ker** [comment]
> required by: world[postgresql-client~12.10-r0]
 
 1. Are you on the latest version of alpine?
 2. Can you please your version of alpine and check if the package is present here: https://pkgs.alpinelinux.org/packages ? 
 3. If it's not, you'll need to find the new name of the package. (usually, just google: "X package for alpine version Y; and you'll find answer easily)
 
 Hope this helps.

**Comment by boschb** [comment]
Hi! 

So I got it to build.  It was not as bad as it could have been, but it certainly did not need to be this troublesome.  The main issue is that that RUN does not play well on apline SH (and probably ASH/BASH too).  I had to convert RUN to exec CMD[] which is odd, but seems to be the only thing that works... (some prior art [here](https://www.baeldung.com/linux/docker-output-redirect#1-changing-the-dockerfile-2)

This is not the best patch I can do, but since my time (and responses here) are limited, here is the current patch that should build on **alpine aarch64**.  I will attempt to test it and clean it up before making a pull, but welcome any early feedback.  I (though probably competent enough) honestly don't play in docker world much,, but I hope to deliver something of value as a first go here.

```
$ cat ~/openwisp-alpine.patch
diff --git a/Makefile b/Makefile
index 92ca244..08bc90f 100644
--- a/Makefile
+++ b/Makefile
@@ -30,7 +30,7 @@ base-build:
        docker build --tag openwisp/openwisp-base:intermedia-system \
                     --file ./images/openwisp_base/Dockerfile \
                     --target SYSTEM ./images/; \
-       docker build --tag openwisp/openwisp-base:intermedia-python \
+       docker build  --tag openwisp/openwisp-base:intermedia-python \
                     --file ./images/openwisp_base/Dockerfile \
                     --target PYTHON ./images/ \
                     $$BUILD_ARGS; \
@@ -43,7 +43,7 @@ nfs-build:
                     --file ./images/openwisp_nfs/Dockerfile ./images/

 compose-build: base-build
-       docker-compose build --parallel
+       docker-compose --verbose build

 # Test
 runtests: develop-runtests
diff --git a/images/openwisp_freeradius/Dockerfile b/images/openwisp_freeradius/Dockerfile
index f94b71a..e361d81 100644
--- a/images/openwisp_freeradius/Dockerfile
+++ b/images/openwisp_freeradius/Dockerfile
@@ -1,12 +1,8 @@
 FROM freeradius/freeradius-server:3.0.26-alpine

 # hadolint ignore=DL3018
-RUN apk add --no-cache --update tzdata~=2022f-r1 postgresql-dev~=13.8-r0 \
-                                postgresql-client~=13.8-r0 && \
-    rm -rf /var/cache/apk/* /tmp/*
-
-RUN addgroup -S freerad && \
-    adduser -S freerad -G freerad
+CMD ["/bin/sh", "-c", "apk add --no-cache --update tzdata~=2023c-r1 postgresql-dev~=13.8-r0 postgresql-client~=13.8-r0"]
+CMD ["/bin/sh", "-c", "addgroup -S freerad && adduser -S freerad -G freerad"]

 CMD ["sh", "init_command.sh"]
 EXPOSE 1812/udp 1813/udp
@@ -15,8 +11,7 @@ EXPOSE 1812/udp 1813/udp
 COPY ./common/init_command.sh \
     ./common/utils.sh ./
 COPY ./openwisp_freeradius/raddb/ /etc/raddb/
-RUN chown -R freerad:root /opt/etc/raddb/ && \
-    chown -R freerad:root /opt/var/log/
+CMD ["/bin/sh", "-c", "chown -R freerad:root /opt/etc/raddb/ && chown -R freerad:root /opt/var/log/"]

 ENV TZ=UTC \
     MODULE_NAME=freeradius \
diff --git a/images/openwisp_nfs/Dockerfile b/images/openwisp_nfs/Dockerfile
index dd16f08..45d6339 100644
--- a/images/openwisp_nfs/Dockerfile
+++ b/images/openwisp_nfs/Dockerfile
@@ -2,7 +2,7 @@ FROM alpine:3.16

 # hadolint ignore=DL3018
 RUN apk add --no-cache --update --verbose \
-            tzdata~=2022f-r1 \
+            tzdata~=2023c-r1 \
             nfs-utils~=2.6.1-r1 && \
     rm -rf /var/cache/apk/* /tmp/*

diff --git a/images/openwisp_nginx/Dockerfile b/images/openwisp_nginx/Dockerfile
index 3e3ad8e..1cbc95f 100644
--- a/images/openwisp_nginx/Dockerfile
+++ b/images/openwisp_nginx/Dockerfile
@@ -1,10 +1,6 @@
 FROM nginx:1.23.3-alpine

-RUN apk add --update --no-cache \
-            openssl~=3.0.8-r0 \
-            certbot~=1.32.0-r0 \
-            certbot-nginx~=1.32.0-r0 && \
-    rm -rf /var/cache/apk/* /tmp/*
+CMD ["/bin/sh", "-c", "apk add --update --no-cache openssl~=3.0.8-r0 certbot~=1.32.0-r0  certbot-nginx~=1.32.0-r0"]

 WORKDIR /etc/nginx/
 CMD ["sh", "init_command.sh"]
@@ -16,7 +12,7 @@ COPY ./common/services.py \
     ./openwisp_nginx/ \
     /etc/nginx/

-RUN pip install --no-cache-dir -r requirements.txt
+CMD ["/bin/sh", "-c", "python -m pip install --no-cache-dir -r requirements.txt"]

 ENV MODULE_NAME=nginx \
     PYTHONUNBUFFERED=1 \
diff --git a/images/openwisp_openvpn/Dockerfile b/images/openwisp_openvpn/Dockerfile
index 5a87d94..a4f500f 100644
--- a/images/openwisp_openvpn/Dockerfile
+++ b/images/openwisp_openvpn/Dockerfile
@@ -1,11 +1,9 @@
 # hadolint ignore=DL3007
-FROM kylemanna/openvpn:2.4
+FROM kylemanna/openvpn
+
+#USER root
+CMD ["/bin/sh/", "-c", "apk add --no-cache --upgrade tzdata~=2023c-r1 postgresql15-client~=15.2-r4 supervisor~=4.2.5-r2"]

-RUN apk add --no-cache \
-            tzdata~=2022a-r0 \
-            postgresql-client~=12.10-r0 \
-            supervisor~=4.2.0-r0 && \
-    rm -rf /var/cache/apk/* /tmp/*
 CMD ["sh", "init_command.sh"]
 EXPOSE 1194

diff --git a/images/openwisp_postfix/Dockerfile b/images/openwisp_postfix/Dockerfile
index 4c680d1..7fed0c6 100644
--- a/images/openwisp_postfix/Dockerfile
+++ b/images/openwisp_postfix/Dockerfile
@@ -1,15 +1,8 @@
-FROM alpine:3.16
+FROM alpine

 WORKDIR /opt/openwisp/
-RUN apk add --no-cache --upgrade \
-            openssl~=1.1.1t-r0 \
-            cyrus-sasl~=2.1.28-r1      \
-            cyrus-sasl-login~=2.1.28-r1 && \
-    apk add --no-cache \
-            postfix~=3.7.3-r0 \
-            rsyslog~=8.2204.1-r0        \
-            tzdata~=2022f-r1 && \
-    rm -rf /tmp/* /var/cache/apk/*
+USER root
+CMD ["/bin/sh", "-c", "apk add --no-cache --upgrade openssl~=3.1.0-r4 cyrus-sasl~=2.1.28-r4 cyrus-sasl-login~=2.1.28-r4 && apk add --no-cache --upgrade postfix~=3.8.0-r1 rsyslog~=8.2304.0-r0 tzdata~=2023c-r1 && rm -rf /tmp/* /var/cache/apk/*"]

 CMD ["sh", "init_command.sh"]
 EXPOSE 25
```
