### ISSUE TITLE
[qa] Use dependency monitoring

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#221]
@nemesisdesign I forgot, what we concluded on locking these versions, in my experience, they don't change often, but when they do, we want to update them as quick as possible, mostly for security reasons.

_Originally posted by @atb00ker in https://github.com/openwisp/docker-openwisp/pull/213#discussion_r872974633_

**Comment by nemesisdesign** [comment]
Suggested by @codesankalp: https://snyk.io/
It's not the first time I hear about this service.

**Comment by nemesifier** [comment]
We are using dependabot.
