### ISSUE TITLE
[bug] OpenVPN tunnels does not work out of the box

### ISSUE THREAD

**Issue by pandafy** [openwisp/docker-openwisp#231]
**Steps to replicate**
1. Start the development environment 
2. Register a device to the development environment. The default VPN template should get automatically applied to the device. 

**Expected Outcome**
An OpenVPN tunnel is established between device and the OpenVPN container. And it is possible to send traffic through it

**Actual Outcome**
OpenVPN on the router fails with following error
```
Thu Jun  9 17:23:26 2022 daemon.err openvpn(default)[9866]: TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)

```

**Comment by dberardo-com** [comment]
running the docker distribution of the openvpn container here ... i see no log, and the container is always restarting in k8s ... do you face this issue too ?
