### ISSUE TITLE
Monitoring missing from docker image openwisp/openwisp-dashboard

### ISSUE THREAD

**Issue by rusitschka** [openwisp/docker-openwisp#243]
The official docker image openwisp/openwisp-dashboard doesn't have

* openwisp_monitoring.monitoring
* openwisp_monitoring.device
* openwisp_monitoring.check

In the list of INSTALLED_APPS. 

How can I enable it?

**Comment by nemesisdesign** [comment]
@rusitschka the monitoring module has been included for a while now, are you building the images or downloading it from somewhere and in this case from where?

**Comment by rusitschka** [comment]
I'm using the one from Docker Hub: https://hub.docker.com/r/openwisp/openwisp-dashboard

**Comment by rusitschka** [comment]
What about the other images? E.g. openwisp-celery only has a `wireguard` tag. No `latest`or `edge`. Also, would it be safer to use `latest` instead of `edge`?
