### ISSUE TITLE
[feature] Allow seting main influxdb retention policy

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/docker-openwisp#249]
Similar to https://github.com/openwisp/ansible-ow-influxdb/issues/12.

**Comment by pandafy** [comment]
@nemesisdesign can this be closed now since it can be configured with a Django setting? 
https://github.com/openwisp/openwisp-monitoring/pull/425

**Comment by nemesisdesign** [comment]
Since it's an important thing, we should have a default value and allow easier editability and document it.
