### ISSUE TITLE
Main branch builds failing to push to docker

### ISSUE THREAD

**Issue by SerialVelocity** [openwisp/docker-openwisp#256]
Hey,

It looks like docker pushes are failing on your master branch. According to dockerhub, it looks like there hasn't been a push since 29 June 2021 (over a year ago).

Would it be possible to get a recent release/tag too?

Thanks

**Comment by atb00ker** [comment]
Hi,

The registry is available here: https://gitlab.com/openwisp/docker-openwisp/container_registry
I see the last edge release was made 4 months ago, there hasn't been a numbered release in a while.

**Comment by SerialVelocity** [comment]
Yes, that lines up with when the builds broke. It was due to this PR:
https://github.com/openwisp/docker-openwisp/pull/245

It tries to login to dockerhub but the credentials are not present. This is before any publish happens (even to gitlab), so the changes made in the last 4 months haven't been published. It looks like the last change was 2 months ago.

I did try building locally but I have to remove some of your overrides, specifically your pins for openssl and tzdata. Since alpine has updated, you cannot downgrade these without breaking the world. Command to fix repo:
```
find . -iname "Dockerfile" -print0 | xargs -0 -n 1 sed -E -i "s# (openssl|tzdata)~?=[0-9a-z.-]+# \1#g"
```

**Comment by nemesisdesign** [comment]
@pandafy for some reason the variable names didn't match what we have in the org secrets anymore.

I tried fixing that but now the build is failing for another reason: https://github.com/openwisp/docker-openwisp/actions/runs/3451666625/jobs/5761111562 . Patches are welcome.

**Comment by nemesisdesign** [comment]
Fixed by https://github.com/openwisp/docker-openwisp/commit/319ff0568b437c0d60d603294853683e76fb0d40 and https://github.com/openwisp/docker-openwisp/commit/319ff0568b437c0d60d603294853683e76fb0d40 .
