### ISSUE TITLE
i am following the auto install but not started

### ISSUE THREAD

**Issue by hassan4mz** [openwisp/docker-openwisp#258]
please help
after finish i am waiting more than 3 hours
but not start 
*******************************************
hassan@wisp:~$ sudo bash setup.sh
Welcome to OpenWISP auto-installation script.
Please ensure following requirements:
  - Fresh instance
  - 2GB RAM (Minimum)
  - Root privileges
  - Supported systems
    - Debian: 10 & 11
    - Ubuntu 18.04, 18.10 & 20.04

You can use -u\--upgrade if you are upgrading from an older version.

Checking your system capabilities...                                   done
Setting up dependencies...                                             done
Setting up docker...                                                   done
Setting up docker-compose...                                           done

OpenWISP Configuration:
OpenWISP Version (leave blank for latest):
Do you have .env file? Enter filepath (leave blank for ad-hoc configuration):
(1/5) Enter dashboard domain: hassan.local
(2/5) Enter API domain (blank for api.local):
(3/5) Enter OpenVPN domain (blank for vpn.local, N to disable module): N
(4/5) Site manager email: hassan4mz50@gmail.com
(5/5) Enter letsencrypt email (leave blank for self-signed certificate):

Downloading docker-openwisp...                                         done
Configuring docker-openwisp...                                         done
Starting images docker-openwisp (this will take a while)...            done

Your setup is ready, your dashboard should be available on https://hassan.local in 2 minutes.

You can login on the dashboard with
    username: admin
    password: admin
Please remember to change these credentials.

Random database user and password generate by the script:
    username: qaH5%5tRzoYUABHGVSVRo7PPfOlxEpnvl&y4d5z+ctKfNJIt/F
    password: R7MkI1D%l84HTQHUkkbj/DN5^*/*v5Nv[=n/liPj7bE2AJVkvb
Please note them, might be helpful for accessing postgresql data in future.
********************************************************************************
on  Brawser and the 80 or 443 not open
Unable to connect

An error occurred during a connection to 10.100.52.222.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by Aryamanz29** [comment]
Container logs : `docker-openwisp_nginx_1`
```bash
root@arya-vm:/home/arya# docker logs -f e786a58b35c2
Generating a RSA private key
.......................++++
.........................................................................................................................................................++++
writing new private key to '/etc/letsencrypt/live/dashboard.openwisp.org/privkey.pem'
-----
Generating a RSA private key
........................................++++
.......................................++++
writing new private key to '/etc/letsencrypt/live/api.openwisp.org/privkey.pem'
-----
Generating a RSA private key
...........................++++
................................................................................................................................................................................................................................................................++++
writing new private key to '/etc/letsencrypt/live/radius.example.com/privkey.pem'
-----
2023/02/27 13:40:57 [emerg] 43#43: host not found in upstream "radius" in /etc/nginx/conf.d/radius.https.conf:71
nginx: [emerg] host not found in upstream "radius" in /etc/nginx/conf.d/radius.https.conf:71
```

**Comment by nemesifier** [comment]
Should be fixed on latest master, please reopen if that's not the case.
