### ISSUE TITLE
[bug] redirect to old domain when clicking on notification

### ISSUE THREAD

**Issue by Bixilon** [openwisp/docker-openwisp#274]
I changed the main domain in `.env` works without a problem, but when I click on a notification (e.g. a device has registered), I am still getting redirected to the old domain.

Somewhere in the data (maybe in the database?) is still the old domain, it should not be used and instead the global variable should be used. Another way of solving this (imho better option) is directly in openwisp, redirects should be relative.

**Comment by nemesisdesign** [comment]
@Bixilon check the site configuration: `/admin/sites/site/`

**Comment by Bixilon** [comment]
Did the trick, why is it not linked in the sitebar?

**Comment by nemesifier** [comment]
> Did the trick, why is it not linked in the sitebar?

You mean why is it not linked in the nav menu?
