### ISSUE TITLE
[tasklist] ensure django settings customizabliity

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#28]
> Allow users to easily configure some django settings:

- [ ] CORS settings
- [x] Sentry logging
- [x] DEFAULT_FROM_EMAIL
- [x] SMTP settings
- [x] language code
- [x] timezone
- [x] Leaflet settings
- [x] default cert validity for django-x509
- [x] default CA validity for django-x509

source: http://openwisp.org/gsoc/ideas-2019.html

**Blocked** What CORS settings need to be configurable?

**Comment by atb00ker** [comment]
What CORS settings need to be configurable?

**Comment by 2stacks** [comment]
The only one I can find in the entire Openwisp code base is `CORS_ORIGIN_ALLOW_ALL = True`.  However, it may be prudent to make any available option configurable https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by atb00ker** [comment]
To the best of my knowledge, `CORS_ORIGIN_ALLOW_ALL = True` is used during development not production, right?
[django-cors-headers](https://pypi.org/project/django-cors-headers/) provides more options for cors, I'll checkout other options asap! :smile:

**Comment by 2stacks** [comment]
+1 for django-cors-headers

**Comment by atb00ker** [comment]
I looked into [django-cors-headers](https://pypi.org/project/django-cors-headers/) but I am still not sure if that's what @nemesisdesign meant!

**Comment by atb00ker** [comment]
Taken care in #96
