### ISSUE TITLE
latest version on dockerhub is lagging behind

### ISSUE THREAD

**Issue by dberardo-com** [openwisp/docker-openwisp#285]
how to find out the version of the server running ?

i cannot find the send command procedure as highlighted here: https://openwisp.io/docs/user/send-commands.html

how to build the latest version within docker ? any info ?

**Comment by dberardo-com** [comment]
what do you mean with edit the code ?

usually when building with docker it is not needed to change any code, but just assign new build-arg at building time. do you mean perhaps that the version arguments have to be changed ? if so, which versions should be used?

i am totally new to this project but i would like to get an updated version of the cloud platform up and running. the current one works fine (in kubernetes) but it is somewhat older.

please let me know

**Comment by dberardo-com** [comment]
please let me know

**Comment by nemesifier** [comment]
https://github.com/openwisp/docker-openwisp/issues/297

Use the images pushed on gitlab in the meantime (more info in the README).
