### ISSUE TITLE
DEPRECATION: distro-info 0.23ubuntu1 has a non-standard version number. pip 23.3

### ISSUE THREAD

**Issue by doreks** [openwisp/docker-openwisp#286]
having this issues installing 

` running build_rust
      
          =============================DEBUG ASSISTANCE=============================
          If you are seeing a compilation error please try the following steps to
          successfully install cryptography:
          1) Upgrade to the latest pip and try again. This will fix errors for most
             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
          2) Read https://cryptography.io/en/latest/installation/ for specific
             instructions for your platform.
          3) Check our frequently asked questions for more information:
             https://cryptography.io/en/latest/faq/
          4) Ensure you have a recent Rust toolchain installed:
             https://cryptography.io/en/latest/installation/#rust
      
          Python: 3.8.10
          platform: Linux-5.4.0-1069-raspi-armv7l-with-glibc2.29
          pip: n/a
          setuptools: 68.0.0
          setuptools_rust: 1.6.0
          rustc: n/a
          =============================DEBUG ASSISTANCE=============================
      
      error: can't find Rust compiler
      
      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
      
      To update pip, run:
      
          pip install --upgrade pip
      
      and then retry package installation.
      
      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      
      This package requires Rust >=1.56.0.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography
  Building wheel for pynacl (pyproject.toml): started
  Building wheel for pynacl (pyproject.toml): still running...
  Building wheel for pynacl (pyproject.toml): still running...
Building wheel for pynacl (pyproject.toml): still running...

  Building wheel for pynacl (pyproject.toml): still running...
Building wheel for pynacl (pyproject.toml): still running...

  Building wheel for pynacl (pyproject.toml): still running...

  Building wheel for pynacl (pyproject.toml): still running...
  Building wheel for pynacl (pyproject.toml): still running...
  Building wheel for pynacl (pyproject.toml): still running...
  Building wheel for pynacl (pyproject.toml): still running...
Building wheel for pynacl (pyproject.toml): still running...
  Building wheel for pynacl (pyproject.toml): still running...
  Building wheel for pynacl (pyproject.toml): still running...
  Building wheel for pynacl (pyproject.toml): still running...
  Building wheel for pynacl (pyproject.toml): still running...

  Building wheel for pynacl (pyproject.toml): still running...
  Building wheel for pynacl (pyproject.toml): still running...
  Building wheel for pynacl (pyproject.toml): finished with status 'done'
  Created wheel for pynacl: filename=PyNaCl-1.5.0-cp38-cp38-linux_armv7l.whl size=642702 sha256=84968e384df9a28c73f57043108335435564e94bb3614c75c1ac15d6b13ec253
  Stored in directory: /root/.cache/pip/wheels/3e/4c/46/6bbb66a5a15a3fa4e336d680ccc6a4ebd556d087d38945ce17
Successfully built dockerpty docopt pynacl
Failed to build bcrypt cryptography
ERROR: Could not build wheels for bcrypt, cryptography, which is required to install pyproject.toml-based projects`

and after run update pip:

`
takezo@brainbox:~$ python3 -m pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /usr/local/lib/python3.8/dist-packages (23.2)
DEPRECATION: distro-info 0.23ubuntu1 has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of distro-info or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
DEPRECATION: python-debian 0.1.36ubuntu1 has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of python-debian or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
`

any support here?

**Comment by nemesifier** [comment]
I think this is solved on the latest master, feel free to reopen if that's not the case.
