### ISSUE TITLE
[dockerfile] Move images under openwisp namespace

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/docker-openwisp#29]
See comment: https://github.com/openwisp/docker-openwisp/pull/23#discussion_r286608264

@hispanico how can this be achieved? Do you know?

**Comment by hispanico** [comment]
I've added @atb00ker as owner of OpenWISP organization on DockerHub

**Comment by atb00ker** [comment]
@hispanico , Perfect! I pushed the images to the `openwisp` organization.
