### ISSUE TITLE
No web access to docker

### ISSUE THREAD

**Issue by Forrest-It** [openwisp/docker-openwisp#292]
I tried installing openwisp-docker on a freshly installed ubuntu 22.04 machine. The installation gave no errors, but I don't have access from the web: with netstat -an I don't see any ports listening on the 443. I didn't understand what it uses as a web server: nginx, or its own web server. I also tried reinstalling the application pre-installing nginx: nothing, I only see a listening port on the 80. Can you help me understand? Thank you

**Comment by nemesifier** [comment]
Should be fixed on latest master, please reopen if that's not the case.
