### ISSUE TITLE
Building images broken on arm64 and x86_64

### ISSUE THREAD

**Issue by danielandross** [openwisp/docker-openwisp#293]
Hi,
currently I am unable to build the images using `docker-compose build` command. It fails at the first image postfix. Tested on arm64 (though unsupported" and two machines with x86_64.
It fails when installing openssl from world.

**Comment by nemesifier** [comment]
This should have fixed it: https://github.com/openwisp/docker-openwisp/commit/f728f899f8307d8d2f838697b61427e8907a1490
