### ISSUE TITLE
[testing] openwisp-orchestration: test certbot script 

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#3]
openwisp-orchestration container's certbot script needs to be tested in a container with public IP address.
(Read conversation below)

**Comment by 2stacks** [comment]
Can you elaborate on the dedicated IP requirement?  Does it matter if its public or private, is it for DNS/NAT etc.  Assigned by Docker network or bound to host IP?

**Comment by atb00ker** [comment]
I want to test [this](https://github.com/openwisp/docker-openwisp/blob/a6970be0f82134d9010807472bbcd4055f8b770d/build/openwisp_orchestration/utils.sh#L4-L15) function. 

`certbot certonly --standalone <...>` will work only if I have domains that certbot can reach. For that I think I'll need a container with public IP.

**Comment by atb00ker** [comment]
orchestration container is now deprecated.
The certbot code is in the nginx container and the certbot script needs to be tested.

**Comment by atb00ker** [comment]
Conversation in #43
