### ISSUE TITLE
Troubles with openwisp-monitoring

### ISSUE THREAD

**Issue by NiceRath** [openwisp/docker-openwisp#307]
Greetings!

As [openwisp-monitoring mentions this repository](https://github.com/openwisp/openwisp-monitoring?tab=readme-ov-file#deploy-it-in-production) I'm trying to get OpenWISP dockerized to work for monitoring our fleet of OpenWRT APs - but had no luck over the last few days.
The documentation and videos on YouTube do not cover the setup-process that well. If I get it working - I'm open to provide some PR's to improve it!

What's my status:
* I'm deploying docker-openwisp using Ansible: https://github.com/NiceRath/ansible-openwisp-dockerized
* It works and I'm able to login to the Admin interface

What is my issue:
* I do not know where to find the [metrics](https://github.com/openwisp/openwisp-monitoring/tree/master?tab=readme-ov-file#default-metrics) as there is no navigation bar the the left of the window
![image](https://github.com/openwisp/docker-openwisp/assets/71257903/8cc2311b-5045-4992-bd42-f7b1c797fa18)

I think I'm missing something basic.. :/

**Comment by nemesifier** [comment]
The version in the screenshot is super old. How are you getting there?

Try with the latest images available on docker hub or gitlab registry.

**Comment by NiceRath** [comment]
I basically used the docker-compose setup as documented: https://github.com/openwisp/docker-openwisp/blob/master/docs/QUICK_SETUP.md

As I had the same issue with the default versions used in the [openwisp_base image](https://github.com/openwisp/docker-openwisp/blob/master/images/openwisp_base/Dockerfile#L30).
So I tried using the [latest releases of all repositories](https://github.com/NiceRath/ansible-openwisp-dockerized/blob/main/defaults/main.yml#L20) using the build-arg overrides. (thought those would be 'stable')

**Comment by nemesifier** [comment]
The version of the UI shown in the screenshot above does not match the versions shown in that YAML file.
The 1.0.X version map are more similar to what you can see on the [OpenWISP demo](https://openwisp.org/demo.html).
