### ISSUE TITLE
Dashboard unliable even after a succefull install

### ISSUE THREAD

**Issue by Ortiz25** [openwisp/docker-openwisp#309]
Is there a way to alter the configs to reach the dash via the servers IP (as the earlier versions) as opposed to domain, I have tried to access the dashboard via the domain dashboard.openwisp.org but to no avail.

**Comment by nemesifier** [comment]
You have several options:

- If it's a prod deployment, use real DNS records
- Add the domain in the local host file as indicated in the REDME:

> To reach the dashboard you may need to add the openwisp domains set in your .env to your hosts file, example: bash -c 'echo "127.0.0.1 dashboard.openwisp.org api.openwisp.org" >> /etc/hosts'

- Add the IP address of the host to ALLOWED_HOSTS https://github.com/openwisp/docker-openwisp/blob/master/docs/ENV.md#django_allowed_hosts

Using IP address in prod is not recommended as this will likely require you to turn of SSL verification on your devices, which is insecure.

If you have more questions please use the [support channels](https://openwisp.org/support.html), github issues are for bug reports only.
