### ISSUE TITLE
[change] Migrate to freeradius 3.2

### ISSUE THREAD

**Issue by nemesifier** [openwisp/docker-openwisp#365]
Freeradius 3.2 is available, we can migrate to it once we're done publishing the incoming release.

**Comment by praptisharma28** [comment]
Is not it already migrated to freeradius 3.2? @nemesifier 
Why this issue?

**Comment by pandafy** [comment]
@praptisharma28 is correct. FreeRADIUS was upgraded to 3.2 in 4293afd30e51b2de6540003f1c8628c933fe9a43 

@nemesifier can this issue be closed?

**Comment by nemesifier** [comment]
Thanks!
