### ISSUE TITLE
[bug] openvpn docker configuration download loop

### ISSUE THREAD

**Issue by Poueck** [openwisp/docker-openwisp#377]
**Describe the bug**
OpenVPN loads its configuration every minutes and restart

**Steps To Reproduce**
1. Start OpenWISP docker containers
2. Tail logs of openvpn docker
3. See openvpn restart every minutes

**Expected behavior**
OpenVPN should restart only when configuration changes on OpenWISP

**System Informatioon:**
 - OS: AlmaLinux release 8.10 (Cerulean Leopard)
 - Docker version: Docker version 26.1.3, build b72abbb

**Comment by Poueck** [comment]
I've found the issue in utils.sh

```
function openvpn_config_download {
	curl --silent --retry 10 --retry-delay 5 --retry-max-time 300\
		--insecure --output vpn.tar.gz \
		${API_INTERNAL}/controller/vpn/download-config/$UUID/?key=$KEY
	curl --silent --insecure -outputO checksum \
		${API_INTERNAL}/controller/vpn/checksum/$UUID/?key=$KEY
	tar xzf vpn.tar.gz
	chmod 600 *.pem
}
```
The curl command to download the checksum file have a "-outputO" parameter. After change to "--output", bug is fixed

**Comment by nemesifier** [comment]
@Poueck thanks for reporting! https://github.com/openwisp/docker-openwisp/pull/379 should fix this.
