### ISSUE TITLE
[bug] openvpn docker don't refresh revoked CRL

### ISSUE THREAD

**Issue by Poueck** [openwisp/docker-openwisp#378]
**Describe the bug**
openvpn docker don't refresh revoked CRL and all client connections are dropped

**Steps To Reproduce**
1. Start OpenWISP docker containers
2. Wait CRL expiration
3. See error in openvpn docker logs

**Expected behavior**
revoked CRL should be keeped up to date

**Screenshots**
`openvpn-1  | Mon Oct 28 16:38:36 2024 xx:xx:xx:xx:xx:xx-router-Syg56REk/xx.xx.xx.xx:52989 VERIFY ERROR: depth=0, error=CRL has expired: C=xx, ST=xx, L=xx, O=xx, emailAddress=xx, CN=xx:xx:xx:xx:xx:xx-router-Syg56REk
`

**System Informatioon:**
 - OS: AlmaLinux release 8.10 (Cerulean Leopard)
 - Docker version: Docker version 26.1.3, build b72abbb

**Comment by Poueck** [comment]
To fix the issue, I found a bug and a missconfiguration

A bug in the revokelist.sh script:
`#!/bin/sh

# This script will be called by cronjob to
# update CRL periodically.
source /utils.sh

default_psql_vars
crl_download
supervisorctl restart openvpn
`
Before calling the 'crl_download' function, I add a call to the 'openvpn_config' function in order to load the CA_UUID variable

The missconfiguration is that in the 'init_command.sh' in openvpn part, the revokelist.sh is scheduled to run at 3:00 every sunday, but it seems that CRL is valid only 24 hours.

**Comment by nemesifier** [comment]
@Poueck thanks for reporting! https://github.com/openwisp/docker-openwisp/pull/379 should fix this.
