### ISSUE TITLE
[bug] OpenVPN container cron scripts save files in /root instead of /

### ISSUE THREAD

**Issue by Poueck** [openwisp/docker-openwisp#388]
**Describe the bug**
The configuration update script and de CRL download script produce files that are written in the current directoy.
Crond set the current directory to /root, but files should be in /
This implies that new CRL file and new config files don't overwrite the existing one and nothing is applied

**Steps To Reproduce**
1. Start the OpenVPN docker
2. Change the configuration of the OpenVPN server in OpenWISP
3. Wait for configuration script run
4. See that configuration files are in /root directory and configuration files in / are still the originals

**Expected behavior**
files in / directory should be overwrited

**System Informatioon:**
 - OS: AlmaLinux release 8.10 (Cerulean Leopard)
 - Docker version: Docker version 26.1.3, build b72abbb

**Comment by Poueck** [comment]
To fix the issue, I locally update crontab lines to
`
*/1 * * * * cd / && sh /openvpn.sh
0 0 * * * cd / && sh /revokelist.sh
`

I notice that restarting OpenVPN is not needed after CRL file download. The file seems to be loaded on each new connection to the OpenVPN server.

**Comment by pandafy** [comment]
> When the crl-verify option is used in OpenVPN, the CRL file will be re-read any time a new client connects or an existing client renegotiates the SSL/TLS connection (by default once per hour). This means that you can update the CRL file while the OpenVPN server daemon is running, and have the new CRL take effect immediately for newly connecting clients. If the client whose certificate you are revoking is already connected, you can restart the server via a signal (SIGUSR1 or SIGHUP) and flush all clients, or you can telnet to the [management interface](https://openvpn.net/community-resources/management-interface/) and explicitly kill the specific client instance object on the server without disturbing other clients.

This is from the [OpenVPN docs](https://openvpn.net/community-resources/revoking-certificates/#:~:text=connection%20being%20dropped.-,CRL%20Notes,-When%20the%C2%A0). 


Restarting the OpenVPN service is required to immediately terminate the existing connection.

**Comment by nemesifier** [comment]
@Poueck we're working on this in https://github.com/openwisp/docker-openwisp/pull/391, feedback is welcome :pray: .
