### ISSUE TITLE
[bug] Auto install script point to tag named "latest"

### ISSUE THREAD

**Issue by nemesifier** [openwisp/docker-openwisp#407]
The auto install script point to tag named "latest", this is problematic because the git tag has to be deleted and recreated whenever a new release comes out, which doesn't seem the right way to use git tags.

We need to find an alternative solution to install the latest available release (we can use the latest release flag provided by git/github).

**Comment by youhaveme9** [comment]
Hey @pandafy 
I'm working on this issue and implemented the function
just making sure if `get_version_from_user` is a good name of the function before raising PR

**Comment by pandafy** [comment]
@youhaveme9 yes, that sounds good.
