### ISSUE TITLE
[bug] Suggest correct hostname for OpenVPN in auto-install script

### ISSUE THREAD

**Issue by youhaveme9** [openwisp/docker-openwisp#419]
**Describe the bug**
While accepting input for vpn domain from user in auto-install script, the script suggest vpn.{domain} and also configure the VPN_DOMAIN to vpn.{domain} in env 

**Expected behavior**
The script should suggest openvpn.{domain} and configure the VPN_DOMAIN to openvpn.{domain}

**Comment by pandafy** [comment]
@youhaveme9 thank you for creating this issue.
