### ISSUE TITLE
[test] Need to test database with sslmode "required"

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#47]
The SSLMODE needs to be set as required and tested.

**Comment by Psycho-Pirate** [comment]
I would like to work on this issue, please guide me through!

**Comment by 2stacks** [comment]
I think the intent was to enable ssl on all or some of the connections to the database.   You can start by reviewing the postgres docs.  It looks like sslmode=require has been deprecated for sslmode=verify-ca.

https://www.postgresql.org/docs/10/libpq-ssl.html

**Comment by Psycho-Pirate** [comment]
I went through the postgres docs, what should i do next?

**Comment by Psycho-Pirate** [comment]
@atb00ker Thank you so much! I will get started on this!

**Comment by TheOneAboveAllTitan** [comment]
Hey @Psycho-Pirate, are you still working on this?

**Comment by atb00ker** [comment]
@TheOneAboveAllTitan Feel free to work on it. :smile:
