### ISSUE TITLE
run openwisp-network-topology periodic tasks

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#51]
Some tasks need to run perodically for openwisp-network-topology which are currently not in a cronjob.
A celery-beat instance or a kubernetes's cronjob object needs to be implemented for this!

**Comment by nemesisdesign** [comment]
See my reply for #50, the management commands in this case are:

- `update_topology`
- `save_snapshot`

**Comment by atb00ker** [comment]
Closed by #60
