### ISSUE TITLE
[bug] freeradius doesn't work with https

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#54]
Error:
```
(1) rest: EXPAND {"username": "%{User-Name}", "password": "%{User-Password}"}
(1) rest: --> {"username": "admin", "password": "admin"}
(1) rest: Processing response header
(1) rest: ERROR: Malformed HTTP header: Status line too short
(1) rest: ERROR: Received 13 bytes of response data: HTTP/2 200
(1) rest: ERROR: Request failed: 23 - Failed writing received data to disk/application
(1) rest: ERROR: Server returned no data
```

The following were first thought of as the cause of the issue but testing proved these theories wrong:
1. `HTTP/2` related bug in upstream: 
Tested using `HTTP/1.1` instead of `HTTP/2`

2. Certificate issue, tested with:
```
tls = {
   tls_check_cert = no
   tls_check_cert_cn = no
}
```

**Comment by pawelplsi** [comment]
Could You provide some details on how to reproduce this bug?

**Comment by atb00ker** [comment]
Lesson learned: document the steps to reproduce.
I can't remember now how to recreate the error, all I remember if we have freeradius with https, we get the error!

**Comment by atb00ker** [comment]
Can't reproduce, haven't seen it in a long while!
