### ISSUE TITLE
[enchancement] Removing psql shell commands

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#64]
Remove psql statements from containers for a more pythonic approach that give proper error codes (like using psycopg2). 
The psql statements are used in the shell script: `common/utils.sh`.

**Blocked**: Read comments on the issue

**Comment by nemesisdesign** [comment]
I have one question: why do you want to introduce this change?
Is there anything that we are not able to do with psql which we would be able to do with python?
Is this the [utils.sh](https://github.com/openwisp/docker-openwisp/blob/master/build/common/utils.sh) file mentioned?

It looks enough clean and readable, so I wonder why do we want to do this.

**Comment by atb00ker** [comment]
@nemesisdesign It's possible that I might have misunderstood you, 
I created this issue in response to [this review](https://github.com/openwisp/docker-openwisp/pull/46#discussion_r310276147) as I thought you were talking about `psql`.

However, I also think that using `psql` has a problem incase of debugging because if there is an error in production, there isn't much logging, hence I thought python can help. :smile:

**Comment by nemesisdesign** [comment]
I remember now. Is that line of `psql` causing any real issue? If it works, we could avoid introducing this change now, unless we have more pressing reasons.

**Comment by atb00ker** [comment]
No, It's not causing any issues presently! :smile:

**Comment by atb00ker** [comment]
Marking this as `wontfix` and closing it for now.
If required in future, we can re-open and discuss this!
