### ISSUE TITLE
[netjsonconfig][OpenVPN] Can't remove `mtu_disc` from OpenWISP generated config.

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#65]
The `mtu_disc` option in the VPN server is not supported in some routers and hence causes OpenVPN not initalize properly without removing:

```
        option mtu_disc 'no'                                               
        option mtu_test '0'
```

Following routers have been tested to have this problem:
- GL.iNET GL-MT300N-V2 Mini Travel Router
- Virtual Machine running OpenWRT 18.06

**Comment by atb00ker** [comment]
Removing `mtu_disc` from advanced mode works, It removes the mtu discovery dropdown. However, the admin UI only container option "off", "on", "maybe" and hence this can't be done from the admin UI.

I suppose since it's possible to remove it from advanced mode, this issue is a false alarm. I am closing it because mistakenly, I thought It can't be done from advance mode. 

Please re-open incase there is something to be done here. :smile:

**Comment by nemesisdesign** [comment]
ok, thanks for updating
