### ISSUE TITLE
[release] automating releases

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#76]
The `make publish` command helps me to put the docker images on docker hub, but that's not enough, we want use `Makefile` to be able:

1. Tag the new release with a version number, example `openwisp/openwisp-base:0.1.0` (Images with `latest` tag should also be uploaded.)
2. User to easily upload images in their own docker hub account, example `atb00ker/openwisp-base:0.1.0`
3. ~Release edge image directly from the master branch as `openwisp/openwisp-base:edge`~

Edit:
- 3rd point taken care by docker hub autobuilds! :smile:

**Comment by marfgold1** [comment]
@atb00ker About semantic versioning/semver, if we want automatic incremental semver, how can we tell `make` to increment which number (major, minor, or patch)? Or should we do it manually?
Also, I see `Images with latest tag should also be uploaded.`, well doesn't every `make publish` command is indeed the latest?

**Comment by atb00ker** [comment]
> @atb00ker About semantic versioning/semver, if we want automatic incremental semver, how can we tell make to increment which number (major, minor, or patch)? Or should we do it manually?

For releasing a version, I would prefer makefile gets the version as manual input, like a file named "VERSION". :smile:

> Also, I see Images with latest tag should also be uploaded., well doesn't every make publish command is indeed the latest?

Yes. I included that point to make sure that some student working on this PR doesn't remove `make publish`

**Comment by atb00ker** [comment]
All the three points of this PR are taken care at : https://github.com/openwisp/docker-openwisp/commit/292528ea42bc07156439ff50f37a1d71bba168cf

Hence, closing, please re-open if anything further is required.
